apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec: #replica set
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:  #pod template
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: rushhav717/app2:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations: 
   alb.ingress.kubernetes.io/scheme: internet-facing
   alb.ingress.kubernetes.io/target-type: ip
   alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
   alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:308731954939:certificate/66b8aa23-46da-440e-a68b-6cbda5f6802c
   alb.ingress.kubernetes.io/group.name: rushhav717
spec:
  ingressClassName: alb
  rules:
    - host: app2.rushhav.fun
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: app2
              port:
                number: 80
